FROM alpine:3.6

MAINTAINER Open System Lab

RUN apk --no-cache update && \
    apk add ca-certificates

COPY bin/cookiemonster-linux-amd64 /usr/local/bin/cookiemonster

EXPOSE 8080

CMD ["/usr/local/bin/cookiemonster", "-inKubeCluster=true"]
