FROM alpine:3.6

MAINTAINER Open System Lab

RUN apk --no-cache update && \
    apk add ca-certificates

COPY bin/cookiemonsterworker-linux-amd64 /usr/local/bin/cookiemonster-worker

EXPOSE 8081

CMD ["/usr/local/bin/cookiemonster-worker"]
